apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring
  name: monitoring
  namespace: monitoring
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: grafana
  selector:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana
  type: LoadBalancer
